DROP TABLE IF EXISTS "INVENTORY";
DROP TABLE IF EXISTS "ITM_MOVEMENT";
DROP TABLE IF EXISTS "LOC";
DROP TABLE IF EXISTS "LOT";
DROP TABLE IF EXISTS "SKU";
DROP TABLE IF EXISTS "UOM";
DROP TABLE IF EXISTS "UOM_CONVERSION";
DROP TABLE IF EXISTS "WHSE";
