// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"time"
)

type INVENTORY struct {
	Loc          string    `json:"loc"`
	Lot          string    `json:"lot"`
	Sku          string    `json:"sku"`
	Qty          string    `json:"qty"`
	Qtyallocated string    `json:"qtyallocated"`
	Qtypicked    string    `json:"qtypicked"`
	Qtyexpected  string    `json:"qtyexpected"`
	CreateDate   time.Time `json:"create_date"`
}

type ITMMOVEMENT struct {
	Type       string    `json:"type"`
	ToLoc      string    `json:"to_loc"`
	FromLoc    string    `json:"from_loc"`
	ToLot      string    `json:"to_lot"`
	FromLot    string    `json:"from_lot"`
	Sku        string    `json:"sku"`
	Qty        string    `json:"qty"`
	CreateDate time.Time `json:"create_date"`
}

type LOC struct {
	Loc        string    `json:"loc"`
	Width      string    `json:"width"`
	Height     string    `json:"height"`
	Length     string    `json:"length"`
	Cube       string    `json:"cube"`
	Type       string    `json:"type"`
	Flag       string    `json:"flag"`
	Status     string    `json:"status"`
	CreateDate time.Time `json:"create_date"`
}

type LOT struct {
	Lot         string    `json:"lot"`
	Lottable01  string    `json:"lottable01"`
	Lottable02  string    `json:"lottable02"`
	Lottable03  string    `json:"lottable03"`
	Lottable04  string    `json:"lottable04"`
	ExpiredDate time.Time `json:"expired_date"`
	CreateDate  time.Time `json:"create_date"`
}

type SKU struct {
	Sku         string    `json:"sku"`
	Whseid      string    `json:"whseid"`
	DefUom      string    `json:"def_uom"`
	Productcode string    `json:"productcode"`
	Serialkey   string    `json:"serialkey"`
	Desc        string    `json:"desc"`
	Enable      bool      `json:"enable"`
	CreateDate  time.Time `json:"create_date"`
}

type UOM struct {
	Uom        string    `json:"uom"`
	Desc       string    `json:"desc"`
	CreateDate time.Time `json:"create_date"`
}

type UOMCONVERSION struct {
	ID         int64     `json:"id"`
	BaseUom    string    `json:"base_uom"`
	TargetUom  string    `json:"target_uom"`
	BaseQty    string    `json:"base_qty"`
	TargetQty  string    `json:"target_qty"`
	CreateDate time.Time `json:"create_date"`
}

type WHSE struct {
	Whseid     string    `json:"whseid"`
	Desc       string    `json:"desc"`
	CreateDate time.Time `json:"create_date"`
}
